-----------------------------------------------
-- Samples with Mouse/Gamepad/Keyboard support
-----------------------------------------------
require("samples.complex_ui.main")
--require("samples.virtual_gamepad.main")
--require("samples.flexContainer.main")
--require("samples.nodegraph.main")
--require("samples.editor.main")

-----------------------------------------------
-- other Samples
-----------------------------------------------
--require("samples.demo_ui.main")
--require("samples.basic_ui.main")		-- This sample uses only the luis core library with it's own set of widgets!
--require("samples.gridLayoutTest.main")
--require("samples.difficulty_curve.main")
--require("samples.demo_game.main")
--require("samples.guess_game.main")
--require("samples.AI_Test.main")
--require("samples.jrpg_battlemenu.main")
--require("samples.test.main")
